name: CI/CD Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Type check
      run: bun run type-check
      
    - name: Build project
      run: bun run build
      
    - name: Run E2E tests
      run: bun run test:quick
      
    - name: Test configuration loading
      run: |
        echo "Testing basic configuration..."
        timeout 10s bun build/index.js --config=tests/configs/basic.yaml || true
        echo "Testing JSON configuration..."
        timeout 10s bun build/index.js --config=tests/configs/basic.json || true
        
    - name: Test environment configuration
      run: |
        echo "Testing environment variables..."
        timeout 10s env MCP_SERVERS="test:npx:user-review-mcp" bun build/index.js || true

  build-check:
    name: Build Verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Build project
      run: bun run build
      
    - name: Verify build artifacts
      run: |
        ls -la build/
        [ -f "build/index.js" ] || { echo "Missing index.js"; exit 1; }
        [ -f "build/aggregator-server.js" ] || { echo "Missing aggregator-server.js"; exit 1; }
        [ -f "build/config.js" ] || { echo "Missing config.js"; exit 1; }
        echo "All build artifacts present ✅"
